[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r capstone_proyek/requirements.txt"
]

[start]
cmd = "uvicorn capstone_proyek.main:app --host 0.0.0.0 --port 8000"
